---
title: "Input specification of Arabic inline characters in Unicode"
author: ""
references:
- id: pournader1
  title: Discussion document for polishing Koranic support in Unicode
  author:
  - family: Pournader
    given: Roozbeh
  container-title: UTC Document L2/09-358R
  URL: 'https://www.unicode.org/L2/L2009/09358r-koranic-status.pdf'
  issued:
    year: 2009
- id: milo1
  title: Arabic Amphibious Characters phonetics, phonology, orthography, calligraphy and typography
  author:
  - family: Milo
    given: Thomas
  container-title: UTC Document L2/13-226
  URL: 'https://unicode.org/L2/L2013/13226-koran-ortho.pdf'
  issued:
    year: 2013
- id: milo2
  title: Arabic Inline Charactersfor Qurʾānic and Classic orthographyin Unicode and computer typography
  author:
  - family: Milo
    given: Thomas
  container-title: UTC Document L2/14-109
  URL: 'https://unicode.org/L2/L2014/14109-inline-chars.pdf'
  issued:
    year: 2014
output:
  bookdown::gitbook:
    css: mystyle.css
    split_by: "none"
    self_contained: yes
    pandoc_args: ["--lua-filter=trn.lua"]
    keep_md: yes
    config:
      toc:
        collapse: section
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit : null
      download: null
      search: yes
      fontsettings:
        theme: white
        family: sans
        size: 2
      sharing:
        facebook: yes
        github: no
        twitter: yes
        linkedin: yes
        weibo: no
        instapaper: no
        vk: no
        all: ['facebook', 'twitter', 'linkedin', 'weibo', 'instapaper']
      info: yes
  pagedown::html_paged:
    pandoc_args: ["--lua-filter=trn.lua"]
    css:
      - mystyle.css
      - default-page
      - default
  pdf_document:
    number_sections: true
    pandoc_args: ["--lua-filter=trn.lua"]
    latex_engine: xelatex
    keep_tex: true
    template: bidi_art_templ.tex
---

# Problem Statement

Unicode currently lacks a consistent and complete specification for handling Arabic inline characters. In this document we will consider two such characters:

1. [#hamzao]{.trn}
2. [E#alif xanjariyyao]{.trn} "Dagger Alef"

## [#hamzao]{.trn}

The case for inline [hamzao]{.trn} has been discussed in some detail in [@pournader1; @milo1 Section IV; @milo2] but, it appears, without much official resolution. There has also been an action item [139-A60](https://www.unicode.org/L2/L2014/14100.htm#139-A60) to address the topic.

We will attempt to summarize the problem here.

Being a later addition to the Arabic script, [hamzao]{.trn} is written as a diacritic on the basic skeletal text. This [hamzao]{.trn} can be written in two different ways:

1. Above a base letter, known as the “seat of the [hamzao]{.trn}”: In writing the Arabic language [hamzao]{.trn} may be seated above a vowel letter: [أ ؤ ئ]{.ar}. It may also be sometimes written below vowel letters, depending on the writing style and vowel mark: [إ ىٕ]{.ar}. In Persian language writing, it may also appear above a `U+0647` [arabic letter heh]{.smallcaps}: [هٔ]{.ar}.
2. After (to the left of) a base letter in the basic skeletal text. This has two sub-cases:
   a. Standalone [hamzao]{.trn}: After a non-joining base letter ([ا د ذ ر ز و]{.ar}) or at the end of a word. In this case, [hamzao]{.trn} is written at the baseline. Examples: [دعاء]{.ar}, [سوء]{.ar}, [عِبْء]{.ar}.
   b. Inline [hamzao]{.trn}: After a joining base letter in the middle of a word. In this case [hamzao]{.trn} is written between the two joining base letters, above the baseline, and without affecting the joining of the two base letters. Examples: [خطيءة]{.ar}, [شيءًا]{.ar}, [بريءين]{.ar}

For a set of rules to determine the seat of the [hamzao]{.trn} and whether [hamzao]{.trn} is to be written inline, see this article: https://adamiturabi.github.io/hamza-rules/

For case (1), Unicode provides [◌ٔ]{.ar} `U+0654` [arabic hamza above]{.smallcaps} and [◌ٕ]{.ar} `U+0655` [arabic hamza below]{.smallcaps} as combining diacritics.

For case (2a), Unicode provides [ء]{.ar} `U+0621` [arabic letter hamza]{.smallcaps}.

It is case (2b) which is problematic and has not been given sufficient attention by the Unicode standard. It would have been sufficient to use [ء]{.ar} `U+0621` [arabic letter hamza]{.smallcaps} and specify that it shall not break the joining of the letter before it with the letter after it. Unfortunately, Unicode specifies that [ء]{.ar} `U+0621` [arabic letter hamza]{.smallcaps} is a breaking character. OpenType shaping engines enforce this (as they rely on Unicode for joining behaviour). Fonts that want to change this behaviour will have to jump through many hoops to achieve it. 

Futhermore, a set of "simplified" [hamzao]{.trn} rules have been proposed by Arabic Language Academy in Cairo where inline [hamzao]{.trn} is approximated with [ئ]{.ar} `U+0626` [arabic letter yeh with hamza above]{.smallcaps}, which between two joining letters looks similar to an inline [hamzao]{.trn} [ـئـ]{.ar}.

Nevertheless, the need still exists to input and display inline [hamzao]{.trn} according to the proper rules without approximating it with [ئ]{.ar}. In order to facilitate this, some fonts propose the use of [ـ]{.ar} `U+0640` [arabic tatweel]{.smallcaps} with [◌ٔ]{.ar} `U+0654` [arabic hamza above]{.smallcaps}. For example, [خطيءة]{.ar} will be input with the following sequence:

Sequence Order | Arabic character | Encoding | Description
:--|:------|:--------|:------
1. |[خ]{.ar}| `U+062E` | [arabic letter khah]{.smallcaps}
2. |[ط]{.ar}| `U+0637` | [arabic letter tah]{.smallcaps}
3. |[ي]{.ar}| `U+064A` | [arabic letter yeh]{.smallcaps}
4. |[ـ]{.ar}| `U+0640` | [arabic tatweel]{.smallcaps}
5. |[◌ٔ]{.ar}| `U+0654` | [arabic hamza above]{.smallcaps}
6. |[ة]{.ar}| `U+0629` | [arabic letter teh marbuta]{.smallcaps}

This solution is not ideal because it introduces a character in the basic skeletal text (`U+0640` [arabic tatweel]{.smallcaps}) which is not part of the word’s spelling. This can also adversely affect computerized search and indexing of text encoded in this manner.

Besides this being an improper hack, this solution will simply not work when inline [hamzao]{.trn} comes between [lAm]{.trn} and [Ealif]{.trn}. In this case [hamzao]{.trn} properly ought not to break the mandatory [lAm]{.trn}-[Ealif]{.trn} ligature [لا]{.ar}. For example, the word [الءاخرة]{.ar} [alEAxirao]{.trn} has a [hamzao]{.trn} between the [lAm]{.trn} and [Ealif]{.trn}. When input with a `U+0640` [arabic tatweel]{.smallcaps}, it will be displayed incorrectly as [الـٔاخرة]{.ar}.

Such words are common in some writing styles of [#qurEAn]{.trn2}ic text. Even in non-[#qurEAn]{.trn2}ic text there are some words which require inline [hamzao]{.trn} between [lAm]{.trn} and [Ealif]{.trn}. For example [مَلَءًا]{.ar} [malaEan]{.trn} and [لَءَّال]{.ar} [laEEAl]{.trn}.

## Dagger Alef

Dagger Alef can also be considered an inline character. Depending on the writing style and intended pronunciation, it can appear either:

1. Above a base letter: [هٰذا]{.ar} [hApA]{.trn}, [ذٰلك]{.ar} [pAlika]{.trn}, [صلوٰة]{.ar} [SalAo]{.trn}, [علىٰ]{.ar} [ealA]{.trn}
2. After a base letter. This two has two sub-cases:
   a. After a non-joining base letter: [صلو ٰت]{.ar} [SalawAt]{.trn}, [صر ٰط]{.ar} [SirAT]{.trn}, [ذ ٰلك]{.ar} [pAlika]{.trn}
   b. After a joining base letter: [هـٰذا]{.ar} [hApA]{.trn}, [أولـٰئك]{.ar} [EulAEika]{.trn}

Unicode provides [◌ٰ]{.ar} `U+0670` [arabic superscript alef]{.smallcaps} to encode Dagger Alef. Being a combining character, `U+0670` [arabic superscript alef]{.smallcaps} is sufficient to encode case (1) above.

Cases (2a) and (2b) do not have a standard specification for being input. Many fonts propose using `U+00A0` [no-break space (nbsp)]{.smallcaps} or `U+202F` [narrow no-break space (nnbsp)]{.smallcaps} combined with `U+0670` [arabic superscript alef]{.smallcaps} for case (2a), and `U+0640` [arabic tatweel]{.smallcaps} combined with `U+0670` [arabic superscript alef]{.smallcaps} for case (2b).

However, this solution is problematic for some of the same reasons as for [hamzao]{.trn}:

1. It introduces characters in the text which are not part of the word’s spelling: [tatweel]{.smallcaps} and [nbsp/nnbsp]{.smallcaps}.
2. The user has to choose between between [tatweel]{.smallcaps} and [nbsp/nnbsp]{.smallcaps} simply on the basis of whether the preceding character is joining or non-joining. The computer’s shaping engine already handles joining of base letters. Therefore, this choice left to the user is non-semantic and unnecessary.
3. It may adversely affect computerized search and indexing.

Other fonts will render the Dagger Alef above the base letter by default but automatically offset the Dagger Alef to the left if a [◌َ]{.ar} `U+064E` [arabic fatha]{.smallcaps} is encoded before it. Thus these fonts can display [هٰذا]{.ar} and [هَـٰذا]{.ar} but (problematically) not [هـٰذا]{.ar}.

## Summary

We may condense the problem statement thus:

Arabic has the need to display inline characters as diacritics that:

1. May generally be either above or after (to the left of) a base character. The two (above and after) are to be differentiated as they may affect pronunciation.
2. Must not affect the joining of base letters.

# Proposed solution

We propose specifying the use of `U+034F` [combining grapheme joiner (cgj)]{.smallcaps} to determine whether a diacritic appears above or after a base letter.

Also that [◌ٔ]{.ar} `U+0654` [arabic hamza above]{.smallcaps} be used for the diacritic inline [hamzao]{.trn} and [◌ٰ]{.ar} `U+0670` [arabic superscript alef]{.smallcaps} continue to be used for the diacritic Dagger Alef.

If the diacritic is to appear above the base letter then it shall be input after the letter without an intermediate [cgj]{.smallcaps}.

If the diacritic is to appear after the base letter then it shall be input after the letter with an intermediate [cgj]{.smallcaps} before the diacritic.

[cgj]{.smallcaps} and/or the diacritic shall not affect the joining of base letters.

[cgj]{.smallcaps} shall prevent any other diacritics before it from normalizing/reordering with the diacritics after it.

We recommend to font developers and typographers that the combination of [cgj]{.smallcaps} followed by [◌ٔ]{.ar} `U+0654` [arabic hamza above]{.smallcaps} after a non-joining letter be rendered identical to [ء]{.ar} `U+0621` [arabic letter hamza]{.smallcaps}.

Here are some examples of the proposed input sequences and the displayed rendering:

Arabic text | Transcription |Character input sequence
:-------|:---------|:---------------
[خطيءة]{.ar} | [xaTIEao]{.trn} | [khah, tah, yeh, **cgj**, hamza above, teh marbuta]{.smallcaps}
[خاطئة]{.ar}  | [xATiEao]{.trn} | [khah, alef, tah, yeh, hamza above, teh marbuta]{.smallcaps}
[لَءّال]{.ar}  | [laEEAl]{.trn} | [lam, fatha, **cgj**, hamza above, shaddah, alef, lam]{.smallcaps}
[هٰذا]{.ar}   | [hApA]{.trn} | [heh, superscript alef, thal, alef]{.smallcaps}
[هـٰذا]{.ar}  | [hApA]{.trn} | [heh, **cgj**, superscript alef, thal, alef]{.smallcaps}
[هَـٰذا]{.ar}  | [hApA]{.trn} | [heh, fatha, **cgj**, superscript alef, thal, alef]{.smallcaps}
[ذٰلك]{.ar}   | [pAlika]{.trn} | [thal, superscript alef, lam, kaf]{.smallcaps}
[ذ ٰلك]{.ar}  | [pAlika]{.trn} | [thal, **cgj**, superscript alef, lam, kaf]{.smallcaps}
[ذَ ٰلك]{.ar}  | [pAlika]{.trn} | [thal, fatha, **cgj**, superscript alef, lam, kaf]{.smallcaps}
[صلوٰة]{.ar}  | [SalAo]{.trn} | [sad, lam, waw, superscript alef, teh marbuta]{.smallcaps}
[صلو ٰت]{.ar} | [SalawAt]{.trn} | [sad, lam, waw, **cgj**, superscript alef, teh]{.smallcaps}
[سمـٰو ٰت]{.ar} | [samAwAt]{.trn} | [seen, meem, **cgj**, superscript alef, waw, **cgj**, superscript alef, teh]{.smallcaps}

# Other inline characters

There exist other inline diacritical characters in Arabic used for displaying [#qurEAn]{.trn2}ic text like:

1. [◌ࣳ]{.ar} `U+08F3` [arabic small high waw]{.smallcaps}. Example: [لِيَسُـࣳءُوا]{.ar} [liyasUEU]{.trn}.
2. [◌ۧ]{.ar} `U+06E7` [arabic small high yeh]{.smallcaps}. Example: [وَلِـِّۧيَ]{.ar} [waliyyiya]{.trn}.

These too are currently input using a `U+0640` [arabic tatweel]{.smallcaps}. However, the proposal to use [cgj]{.smallcaps} should work here as well. Note that, Unicode has separate non-joining characters corresponding to the above which, strictly speaking, will no longer be necessary:

1. [ۥ]{.ar} `U+06E5` [arabic small waw]{.smallcaps}.
2. [ۦ]{.ar} `U+06E6` [arabic small yeh]{.smallcaps}.

But similar to the case of non-joining [hamzao]{.trn}, we recommend, for example, that the sequence [cgj]{.smallcaps}, [◌ࣳ]{.ar} `U+08F3` [arabic small high waw]{.smallcaps} after a non-joining base letter be displayed identical to [ۥ]{.ar} `U+06E5` [arabic small waw]{.smallcaps}.

# References
